import { addOutboundTicketAttribution } from "@/lib/outbound-ticket-attribution";
import { sortShowtimes } from "@/lib/showtime-sort";

/**
 * One canonical screening row at the public read boundary. The public UI still
 * consumes grouped showtimes, so the adapter lives here independently of which
 * table the production loader currently reads.
 */
export type ScreeningReadRow = {
  movie_id: string;
  cinema_id: string;
  starts_at: string;
  local_date: string;
  local_time: string;
  hall: string;
  ticket_url: string | null;
  formats: string[] | null;
  languages: string[] | null;
  events: string[] | null;
};

export type ScreeningIndexReadRow = Pick<
  ScreeningReadRow,
  "movie_id" | "cinema_id" | "local_date" | "local_time" | "formats" | "languages" | "events"
>;

export type UiShowtime = {
  movieId: string;
  cinemaId: string;
  date: string;
  times: string[];
  hall: string;
  bookingUrl: string | null;
  ticketUrls: string[];
  formats: string[];
  languages: string[];
  events: string[];
};

export type UiShowtimeIndexRow = {
  movieId: string;
  cinemaId: string;
  date: string;
  times: string[];
  formats: string[];
  languages: string[];
  events: string[];
};

type ShowtimeGroup = UiShowtime & {
  slots: Array<{ time: string; startsAt: string; ticketUrl: string | null }>;
};

const addUnique = (target: string[], values: string[] | null | undefined) => {
  for (const value of values ?? []) if (value && !target.includes(value)) target.push(value);
};

const tagSignature = (row: {
  formats?: string[] | null;
  languages?: string[] | null;
  events?: string[] | null;
}) =>
  [row.formats ?? [], row.languages ?? [], row.events ?? []]
    .map((values) => [...values].sort().join("\u001f"))
    .join("\u001e");

/**
 * Repair eBillet URLs generated by the old Lanterna importer.
 *
 * Old (invalid): https://flow.ebillet.dk/booking/<movie>/<showtime>?organizerIds=<org>
 * Current:       https://flow.ebillet.dk/billetter/<movie>/<showtime>?org=<org>
 *
 * This read-boundary rewrite makes already-stored production rows work as soon
 * as the frontend is deployed; the importer now writes the current format for
 * all future syncs.
 */
export function normalizeTicketUrl(value: string | null | undefined): string | null {
  const raw = value?.trim();
  if (!raw) return null;

  try {
    const url = new URL(raw);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    if (url.hostname !== "flow.ebillet.dk") return addOutboundTicketAttribution(raw);

    const match = url.pathname.match(/^\/booking\/(\d+)\/(\d+)\/?$/);
    const organizerId = url.searchParams.get("organizerIds");
    if (!match || !organizerId || !/^\d+$/.test(organizerId)) return raw;

    return `https://flow.ebillet.dk/billetter/${match[1]}/${match[2]}?org=${organizerId}`;
  } catch {
    return null;
  }
}

/**
 * Convert one-row-per-screening canonical data into the unchanged UI contract.
 * Ticket URLs remain aligned with the exact screening after sorting.
 */
export function groupScreeningsForUi(rows: ScreeningReadRow[]): UiShowtime[] {
  const groups = new Map<string, ShowtimeGroup>();

  for (const row of rows) {
    // Tags belong to one physical screening, not to every time in the same
    // movie/cinema/date/hall bucket. Keep distinct tag combinations separate
    // until all active filters have been applied.
    const key = `${row.movie_id}|${row.cinema_id}|${row.local_date}|${row.hall}|${tagSignature(row)}`;
    let group = groups.get(key);
    if (!group) {
      group = {
        movieId: row.movie_id,
        cinemaId: row.cinema_id,
        date: row.local_date,
        times: [],
        hall: row.hall,
        bookingUrl: null,
        ticketUrls: [],
        formats: [],
        languages: [],
        events: [],
        slots: [],
      };
      groups.set(key, group);
    }

    group.slots.push({
      time: row.local_time.slice(0, 5),
      startsAt: row.starts_at,
      ticketUrl: normalizeTicketUrl(row.ticket_url),
    });
    addUnique(group.formats, row.formats);
    addUnique(group.languages, row.languages);
    addUnique(group.events, row.events);
  }

  const result: UiShowtime[] = [];
  for (const group of groups.values()) {
    group.slots.sort((a, b) => a.startsAt.localeCompare(b.startsAt));
    const ticketUrls = group.slots.map((slot) => slot.ticketUrl ?? "");
    result.push({
      movieId: group.movieId,
      cinemaId: group.cinemaId,
      date: group.date,
      times: group.slots.map((slot) => slot.time),
      hall: group.hall,
      bookingUrl: group.slots.find((slot) => slot.ticketUrl)?.ticketUrl ?? null,
      ticketUrls,
      formats: group.formats,
      languages: group.languages,
      events: group.events,
    });
  }

  return sortShowtimes(result);
}

/**
 * Homepage filters keep one row per movie/cinema/date/tag combination. This
 * lets combined time/tag filters match the same physical screening instead of
 * cross-matching an event at noon with an ordinary evening screening.
 */
export function groupScreeningIndexForUi(rows: ScreeningIndexReadRow[]): UiShowtimeIndexRow[] {
  const groups = new Map<string, UiShowtimeIndexRow>();
  for (const row of rows) {
    const key = `${row.movie_id}|${row.cinema_id}|${row.local_date}|${tagSignature(row)}`;
    const group = groups.get(key) ?? {
      movieId: row.movie_id,
      cinemaId: row.cinema_id,
      date: row.local_date,
      times: [],
      formats: [],
      languages: [],
      events: [],
    };
    addUnique(group.times, [row.local_time.slice(0, 5)]);
    addUnique(group.formats, row.formats);
    addUnique(group.languages, row.languages);
    addUnique(group.events, row.events);
    groups.set(key, group);
  }
  return [...groups.values()]
    .map((group) => ({ ...group, times: group.times.sort((a, b) => a.localeCompare(b)) }))
    .sort(
      (a, b) =>
        a.date.localeCompare(b.date) ||
        a.movieId.localeCompare(b.movieId) ||
        a.cinemaId.localeCompare(b.cinemaId),
    );
}
