/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityRouteImport } from './routes/$city'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapCinemasDotxmlRouteImport } from './routes/sitemap-cinemas[.]xml'
import { Route as SitemapCityMoviesDotxmlRouteImport } from './routes/sitemap-city-movies[.]xml'
import { Route as SitemapCoreDotxmlRouteImport } from './routes/sitemap-core[.]xml'
import { Route as SitemapMoviesDotxmlRouteImport } from './routes/sitemap-movies[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CityIndexRouteImport } from './routes/$city.index'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BiografIndexRouteImport } from './routes/biograf.index'
import { Route as BiografSlugRouteImport } from './routes/biograf.$slug'
import { Route as ByCityRouteImport } from './routes/by.$city'
import { Route as FilmIndexRouteImport } from './routes/film.index'
import { Route as FilmSlugRouteImport } from './routes/film.$slug'
import { Route as CityFilmSlugRouteImport } from './routes/$city.film.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminDeniedRouteImport } from './routes/_authenticated/admin.denied'
import { Route as AuthenticatedAdminEbilletRouteImport } from './routes/_authenticated/admin.ebillet'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin.pipeline'
import { Route as ApiPublicEbilletSyncRouteImport } from './routes/api/public/ebillet-sync'
import { Route as ApiPublicImportHealthRouteImport } from './routes/api/public/import-health'
import { Route as ApiPublicKultunautImportRouteImport } from './routes/api/public/kultunaut-import'
import { Route as AuthenticatedAdminImportJobIdRouteImport } from './routes/_authenticated/admin.import_.$jobId'
import { Route as ApiPublicKultunautImportProcessRouteImport } from './routes/api/public/kultunaut-import.process'
import { Route as ApiPublicKultunautImportStatusRouteImport } from './routes/api/public/kultunaut-import.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCinemasDotxmlRoute = SitemapCinemasDotxmlRouteImport.update({
  id: '/sitemap-cinemas.xml',
  path: '/sitemap-cinemas.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCityMoviesDotxmlRoute = SitemapCityMoviesDotxmlRouteImport.update({
  id: '/sitemap-city-movies.xml',
  path: '/sitemap-city-movies.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCoreDotxmlRoute = SitemapCoreDotxmlRouteImport.update({
  id: '/sitemap-core.xml',
  path: '/sitemap-core.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMoviesDotxmlRoute = SitemapMoviesDotxmlRouteImport.update({
  id: '/sitemap-movies.xml',
  path: '/sitemap-movies.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityRoute,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BiografIndexRoute = BiografIndexRouteImport.update({
  id: '/biograf/',
  path: '/biograf/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografSlugRoute = BiografSlugRouteImport.update({
  id: '/biograf/$slug',
  path: '/biograf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ByCityRoute = ByCityRouteImport.update({
  id: '/by/$city',
  path: '/by/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIndexRoute = FilmIndexRouteImport.update({
  id: '/film/',
  path: '/film/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmSlugRoute = FilmSlugRouteImport.update({
  id: '/film/$slug',
  path: '/film/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CityFilmSlugRoute = CityFilmSlugRouteImport.update({
  id: '/film/$slug',
  path: '/film/$slug',
  getParentRoute: () => CityRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDeniedRoute =
  AuthenticatedAdminDeniedRouteImport.update({
    id: '/admin/denied',
    path: '/admin/denied',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEbilletRoute =
  AuthenticatedAdminEbilletRouteImport.update({
    id: '/admin/ebillet',
    path: '/admin/ebillet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/admin/pipeline',
    path: '/admin/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicEbilletSyncRoute = ApiPublicEbilletSyncRouteImport.update({
  id: '/api/public/ebillet-sync',
  path: '/api/public/ebillet-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportHealthRoute = ApiPublicImportHealthRouteImport.update({
  id: '/api/public/import-health',
  path: '/api/public/import-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKultunautImportRoute =
  ApiPublicKultunautImportRouteImport.update({
    id: '/api/public/kultunaut-import',
    path: '/api/public/kultunaut-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminImportJobIdRoute =
  AuthenticatedAdminImportJobIdRouteImport.update({
    id: '/admin/import_/$jobId',
    path: '/admin/import/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicKultunautImportProcessRoute =
  ApiPublicKultunautImportProcessRouteImport.update({
    id: '/process',
    path: '/process',
    getParentRoute: () => ApiPublicKultunautImportRoute,
  } as any)
const ApiPublicKultunautImportStatusRoute =
  ApiPublicKultunautImportStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiPublicKultunautImportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city': typeof CityRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-cinemas.xml': typeof SitemapCinemasDotxmlRoute
  '/sitemap-city-movies.xml': typeof SitemapCityMoviesDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/$city/': typeof CityIndexRoute
  '/biograf/': typeof BiografIndexRoute
  '/film/': typeof FilmIndexRoute
  '/$city/film/$slug': typeof CityFilmSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/denied': typeof AuthenticatedAdminDeniedRoute
  '/admin/ebillet': typeof AuthenticatedAdminEbilletRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/api/public/ebillet-sync': typeof ApiPublicEbilletSyncRoute
  '/api/public/import-health': typeof ApiPublicImportHealthRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/import/$jobId': typeof AuthenticatedAdminImportJobIdRoute
  '/api/public/kultunaut-import/process': typeof ApiPublicKultunautImportProcessRoute
  '/api/public/kultunaut-import/status': typeof ApiPublicKultunautImportStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-cinemas.xml': typeof SitemapCinemasDotxmlRoute
  '/sitemap-city-movies.xml': typeof SitemapCityMoviesDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/$city': typeof CityIndexRoute
  '/biograf': typeof BiografIndexRoute
  '/film': typeof FilmIndexRoute
  '/$city/film/$slug': typeof CityFilmSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/denied': typeof AuthenticatedAdminDeniedRoute
  '/admin/ebillet': typeof AuthenticatedAdminEbilletRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/api/public/ebillet-sync': typeof ApiPublicEbilletSyncRoute
  '/api/public/import-health': typeof ApiPublicImportHealthRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/import/$jobId': typeof AuthenticatedAdminImportJobIdRoute
  '/api/public/kultunaut-import/process': typeof ApiPublicKultunautImportProcessRoute
  '/api/public/kultunaut-import/status': typeof ApiPublicKultunautImportStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$city': typeof CityRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-cinemas.xml': typeof SitemapCinemasDotxmlRoute
  '/sitemap-city-movies.xml': typeof SitemapCityMoviesDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/$city/': typeof CityIndexRoute
  '/biograf/': typeof BiografIndexRoute
  '/film/': typeof FilmIndexRoute
  '/$city/film/$slug': typeof CityFilmSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/denied': typeof AuthenticatedAdminDeniedRoute
  '/_authenticated/admin/ebillet': typeof AuthenticatedAdminEbilletRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/api/public/ebillet-sync': typeof ApiPublicEbilletSyncRoute
  '/api/public/import-health': typeof ApiPublicImportHealthRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/import_/$jobId': typeof AuthenticatedAdminImportJobIdRoute
  '/api/public/kultunaut-import/process': typeof ApiPublicKultunautImportProcessRoute
  '/api/public/kultunaut-import/status': typeof ApiPublicKultunautImportStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap-cinemas.xml'
    | '/sitemap-city-movies.xml'
    | '/sitemap-core.xml'
    | '/sitemap-movies.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/$city/'
    | '/biograf/'
    | '/film/'
    | '/$city/film/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/analytics'
    | '/admin/denied'
    | '/admin/ebillet'
    | '/admin/import'
    | '/admin/pipeline'
    | '/api/public/ebillet-sync'
    | '/api/public/import-health'
    | '/api/public/kultunaut-import'
    | '/admin/'
    | '/admin/import/$jobId'
    | '/api/public/kultunaut-import/process'
    | '/api/public/kultunaut-import/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap-cinemas.xml'
    | '/sitemap-city-movies.xml'
    | '/sitemap-core.xml'
    | '/sitemap-movies.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/$city'
    | '/biograf'
    | '/film'
    | '/$city/film/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/analytics'
    | '/admin/denied'
    | '/admin/ebillet'
    | '/admin/import'
    | '/admin/pipeline'
    | '/api/public/ebillet-sync'
    | '/api/public/import-health'
    | '/api/public/kultunaut-import'
    | '/admin'
    | '/admin/import/$jobId'
    | '/api/public/kultunaut-import/process'
    | '/api/public/kultunaut-import/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$city'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/sitemap-cinemas.xml'
    | '/sitemap-city-movies.xml'
    | '/sitemap-core.xml'
    | '/sitemap-movies.xml'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/$city/'
    | '/biograf/'
    | '/film/'
    | '/$city/film/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/denied'
    | '/_authenticated/admin/ebillet'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/pipeline'
    | '/api/public/ebillet-sync'
    | '/api/public/import-health'
    | '/api/public/kultunaut-import'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/import_/$jobId'
    | '/api/public/kultunaut-import/process'
    | '/api/public/kultunaut-import/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CityRoute: typeof CityRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapCinemasDotxmlRoute: typeof SitemapCinemasDotxmlRoute
  SitemapCityMoviesDotxmlRoute: typeof SitemapCityMoviesDotxmlRoute
  SitemapCoreDotxmlRoute: typeof SitemapCoreDotxmlRoute
  SitemapMoviesDotxmlRoute: typeof SitemapMoviesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BiografSlugRoute: typeof BiografSlugRoute
  ByCityRoute: typeof ByCityRoute
  FilmSlugRoute: typeof FilmSlugRoute
  BiografIndexRoute: typeof BiografIndexRoute
  FilmIndexRoute: typeof FilmIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicEbilletSyncRoute: typeof ApiPublicEbilletSyncRoute
  ApiPublicImportHealthRoute: typeof ApiPublicImportHealthRoute
  ApiPublicKultunautImportRoute: typeof ApiPublicKultunautImportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city': {
      id: '/$city'
      path: '/$city'
      fullPath: '/$city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-cinemas.xml': {
      id: '/sitemap-cinemas.xml'
      path: '/sitemap-cinemas.xml'
      fullPath: '/sitemap-cinemas.xml'
      preLoaderRoute: typeof SitemapCinemasDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-city-movies.xml': {
      id: '/sitemap-city-movies.xml'
      path: '/sitemap-city-movies.xml'
      fullPath: '/sitemap-city-movies.xml'
      preLoaderRoute: typeof SitemapCityMoviesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-core.xml': {
      id: '/sitemap-core.xml'
      path: '/sitemap-core.xml'
      fullPath: '/sitemap-core.xml'
      preLoaderRoute: typeof SitemapCoreDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-movies.xml': {
      id: '/sitemap-movies.xml'
      path: '/sitemap-movies.xml'
      fullPath: '/sitemap-movies.xml'
      preLoaderRoute: typeof SitemapMoviesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/': {
      id: '/$city/'
      path: '/'
      fullPath: '/$city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof CityRoute
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biograf/': {
      id: '/biograf/'
      path: '/biograf'
      fullPath: '/biograf/'
      preLoaderRoute: typeof BiografIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biograf/$slug': {
      id: '/biograf/$slug'
      path: '/biograf/$slug'
      fullPath: '/biograf/$slug'
      preLoaderRoute: typeof BiografSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/by/$city': {
      id: '/by/$city'
      path: '/by/$city'
      fullPath: '/by/$city'
      preLoaderRoute: typeof ByCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/': {
      id: '/film/'
      path: '/film'
      fullPath: '/film/'
      preLoaderRoute: typeof FilmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$slug': {
      id: '/film/$slug'
      path: '/film/$slug'
      fullPath: '/film/$slug'
      preLoaderRoute: typeof FilmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/film/$slug': {
      id: '/$city/film/$slug'
      path: '/film/$slug'
      fullPath: '/$city/film/$slug'
      preLoaderRoute: typeof CityFilmSlugRouteImport
      parentRoute: typeof CityRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/denied': {
      id: '/_authenticated/admin/denied'
      path: '/admin/denied'
      fullPath: '/admin/denied'
      preLoaderRoute: typeof AuthenticatedAdminDeniedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ebillet': {
      id: '/_authenticated/admin/ebillet'
      path: '/admin/ebillet'
      fullPath: '/admin/ebillet'
      preLoaderRoute: typeof AuthenticatedAdminEbilletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ebillet-sync': {
      id: '/api/public/ebillet-sync'
      path: '/api/public/ebillet-sync'
      fullPath: '/api/public/ebillet-sync'
      preLoaderRoute: typeof ApiPublicEbilletSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-health': {
      id: '/api/public/import-health'
      path: '/api/public/import-health'
      fullPath: '/api/public/import-health'
      preLoaderRoute: typeof ApiPublicImportHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kultunaut-import': {
      id: '/api/public/kultunaut-import'
      path: '/api/public/kultunaut-import'
      fullPath: '/api/public/kultunaut-import'
      preLoaderRoute: typeof ApiPublicKultunautImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/import_/$jobId': {
      id: '/_authenticated/admin/import_/$jobId'
      path: '/admin/import/$jobId'
      fullPath: '/admin/import/$jobId'
      preLoaderRoute: typeof AuthenticatedAdminImportJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/kultunaut-import/process': {
      id: '/api/public/kultunaut-import/process'
      path: '/process'
      fullPath: '/api/public/kultunaut-import/process'
      preLoaderRoute: typeof ApiPublicKultunautImportProcessRouteImport
      parentRoute: typeof ApiPublicKultunautImportRoute
    }
    '/api/public/kultunaut-import/status': {
      id: '/api/public/kultunaut-import/status'
      path: '/status'
      fullPath: '/api/public/kultunaut-import/status'
      preLoaderRoute: typeof ApiPublicKultunautImportStatusRouteImport
      parentRoute: typeof ApiPublicKultunautImportRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminDeniedRoute: typeof AuthenticatedAdminDeniedRoute
  AuthenticatedAdminEbilletRoute: typeof AuthenticatedAdminEbilletRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminImportJobIdRoute: typeof AuthenticatedAdminImportJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminDeniedRoute: AuthenticatedAdminDeniedRoute,
  AuthenticatedAdminEbilletRoute: AuthenticatedAdminEbilletRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminImportJobIdRoute: AuthenticatedAdminImportJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CityRouteChildren {
  CityIndexRoute: typeof CityIndexRoute
  CityFilmSlugRoute: typeof CityFilmSlugRoute
}

const CityRouteChildren: CityRouteChildren = {
  CityIndexRoute: CityIndexRoute,
  CityFilmSlugRoute: CityFilmSlugRoute,
}

const CityRouteWithChildren = CityRoute._addFileChildren(CityRouteChildren)

interface ApiPublicKultunautImportRouteChildren {
  ApiPublicKultunautImportProcessRoute: typeof ApiPublicKultunautImportProcessRoute
  ApiPublicKultunautImportStatusRoute: typeof ApiPublicKultunautImportStatusRoute
}

const ApiPublicKultunautImportRouteChildren: ApiPublicKultunautImportRouteChildren =
  {
    ApiPublicKultunautImportProcessRoute: ApiPublicKultunautImportProcessRoute,
    ApiPublicKultunautImportStatusRoute: ApiPublicKultunautImportStatusRoute,
  }

const ApiPublicKultunautImportRouteWithChildren =
  ApiPublicKultunautImportRoute._addFileChildren(
    ApiPublicKultunautImportRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CityRoute: CityRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapCinemasDotxmlRoute: SitemapCinemasDotxmlRoute,
  SitemapCityMoviesDotxmlRoute: SitemapCityMoviesDotxmlRoute,
  SitemapCoreDotxmlRoute: SitemapCoreDotxmlRoute,
  SitemapMoviesDotxmlRoute: SitemapMoviesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BiografSlugRoute: BiografSlugRoute,
  ByCityRoute: ByCityRoute,
  FilmSlugRoute: FilmSlugRoute,
  BiografIndexRoute: BiografIndexRoute,
  FilmIndexRoute: FilmIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicEbilletSyncRoute: ApiPublicEbilletSyncRoute,
  ApiPublicImportHealthRoute: ApiPublicImportHealthRoute,
  ApiPublicKultunautImportRoute: ApiPublicKultunautImportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
