/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmSlugRouteImport } from './routes/film.$slug'
import { Route as ByCityRouteImport } from './routes/by.$city'
import { Route as BiografSlugRouteImport } from './routes/biograf.$slug'
import { Route as ApiPublicKultunautImportRouteImport } from './routes/api/public/kultunaut-import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmSlugRoute = FilmSlugRouteImport.update({
  id: '/film/$slug',
  path: '/film/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ByCityRoute = ByCityRouteImport.update({
  id: '/by/$city',
  path: '/by/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografSlugRoute = BiografSlugRouteImport.update({
  id: '/biograf/$slug',
  path: '/biograf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKultunautImportRoute =
  ApiPublicKultunautImportRouteImport.update({
    id: '/api/public/kultunaut-import',
    path: '/api/public/kultunaut-import',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/api/public/kultunaut-import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/api/public/kultunaut-import'
  id:
    | '__root__'
    | '/'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/api/public/kultunaut-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiografSlugRoute: typeof BiografSlugRoute
  ByCityRoute: typeof ByCityRoute
  FilmSlugRoute: typeof FilmSlugRoute
  ApiPublicKultunautImportRoute: typeof ApiPublicKultunautImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$slug': {
      id: '/film/$slug'
      path: '/film/$slug'
      fullPath: '/film/$slug'
      preLoaderRoute: typeof FilmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/by/$city': {
      id: '/by/$city'
      path: '/by/$city'
      fullPath: '/by/$city'
      preLoaderRoute: typeof ByCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biograf/$slug': {
      id: '/biograf/$slug'
      path: '/biograf/$slug'
      fullPath: '/biograf/$slug'
      preLoaderRoute: typeof BiografSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kultunaut-import': {
      id: '/api/public/kultunaut-import'
      path: '/api/public/kultunaut-import'
      fullPath: '/api/public/kultunaut-import'
      preLoaderRoute: typeof ApiPublicKultunautImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiografSlugRoute: BiografSlugRoute,
  ByCityRoute: ByCityRoute,
  FilmSlugRoute: FilmSlugRoute,
  ApiPublicKultunautImportRoute: ApiPublicKultunautImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
