/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmSlugRouteImport } from './routes/film.$slug'
import { Route as ByCityRouteImport } from './routes/by.$city'
import { Route as BiografSlugRouteImport } from './routes/biograf.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicKultunautImportRouteImport } from './routes/api/public/kultunaut-import'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicKultunautImportStatusRouteImport } from './routes/api/public/kultunaut-import.status'
import { Route as ApiPublicKultunautImportProcessRouteImport } from './routes/api/public/kultunaut-import.process'
import { Route as AuthenticatedAdminImportJobIdRouteImport } from './routes/_authenticated/admin.import_.$jobId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmSlugRoute = FilmSlugRouteImport.update({
  id: '/film/$slug',
  path: '/film/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ByCityRoute = ByCityRouteImport.update({
  id: '/by/$city',
  path: '/by/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografSlugRoute = BiografSlugRouteImport.update({
  id: '/biograf/$slug',
  path: '/biograf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKultunautImportRoute =
  ApiPublicKultunautImportRouteImport.update({
    id: '/api/public/kultunaut-import',
    path: '/api/public/kultunaut-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKultunautImportStatusRoute =
  ApiPublicKultunautImportStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiPublicKultunautImportRoute,
  } as any)
const ApiPublicKultunautImportProcessRoute =
  ApiPublicKultunautImportProcessRouteImport.update({
    id: '/process',
    path: '/process',
    getParentRoute: () => ApiPublicKultunautImportRoute,
  } as any)
const AuthenticatedAdminImportJobIdRoute =
  AuthenticatedAdminImportJobIdRouteImport.update({
    id: '/admin/import_/$jobId',
    path: '/admin/import/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRouteWithChildren
  '/admin/import/$jobId': typeof AuthenticatedAdminImportJobIdRoute
  '/api/public/kultunaut-import/process': typeof ApiPublicKultunautImportProcessRoute
  '/api/public/kultunaut-import/status': typeof ApiPublicKultunautImportStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRouteWithChildren
  '/admin/import/$jobId': typeof AuthenticatedAdminImportJobIdRoute
  '/api/public/kultunaut-import/process': typeof ApiPublicKultunautImportProcessRoute
  '/api/public/kultunaut-import/status': typeof ApiPublicKultunautImportStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/biograf/$slug': typeof BiografSlugRoute
  '/by/$city': typeof ByCityRoute
  '/film/$slug': typeof FilmSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/api/public/kultunaut-import': typeof ApiPublicKultunautImportRouteWithChildren
  '/_authenticated/admin/import_/$jobId': typeof AuthenticatedAdminImportJobIdRoute
  '/api/public/kultunaut-import/process': typeof ApiPublicKultunautImportProcessRoute
  '/api/public/kultunaut-import/status': typeof ApiPublicKultunautImportStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/import'
    | '/api/public/kultunaut-import'
    | '/admin/import/$jobId'
    | '/api/public/kultunaut-import/process'
    | '/api/public/kultunaut-import/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/import'
    | '/api/public/kultunaut-import'
    | '/admin/import/$jobId'
    | '/api/public/kultunaut-import/process'
    | '/api/public/kultunaut-import/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/biograf/$slug'
    | '/by/$city'
    | '/film/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/import'
    | '/api/public/kultunaut-import'
    | '/_authenticated/admin/import_/$jobId'
    | '/api/public/kultunaut-import/process'
    | '/api/public/kultunaut-import/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BiografSlugRoute: typeof BiografSlugRoute
  ByCityRoute: typeof ByCityRoute
  FilmSlugRoute: typeof FilmSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicKultunautImportRoute: typeof ApiPublicKultunautImportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$slug': {
      id: '/film/$slug'
      path: '/film/$slug'
      fullPath: '/film/$slug'
      preLoaderRoute: typeof FilmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/by/$city': {
      id: '/by/$city'
      path: '/by/$city'
      fullPath: '/by/$city'
      preLoaderRoute: typeof ByCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biograf/$slug': {
      id: '/biograf/$slug'
      path: '/biograf/$slug'
      fullPath: '/biograf/$slug'
      preLoaderRoute: typeof BiografSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kultunaut-import': {
      id: '/api/public/kultunaut-import'
      path: '/api/public/kultunaut-import'
      fullPath: '/api/public/kultunaut-import'
      preLoaderRoute: typeof ApiPublicKultunautImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kultunaut-import/status': {
      id: '/api/public/kultunaut-import/status'
      path: '/status'
      fullPath: '/api/public/kultunaut-import/status'
      preLoaderRoute: typeof ApiPublicKultunautImportStatusRouteImport
      parentRoute: typeof ApiPublicKultunautImportRoute
    }
    '/api/public/kultunaut-import/process': {
      id: '/api/public/kultunaut-import/process'
      path: '/process'
      fullPath: '/api/public/kultunaut-import/process'
      preLoaderRoute: typeof ApiPublicKultunautImportProcessRouteImport
      parentRoute: typeof ApiPublicKultunautImportRoute
    }
    '/_authenticated/admin/import_/$jobId': {
      id: '/_authenticated/admin/import_/$jobId'
      path: '/admin/import/$jobId'
      fullPath: '/admin/import/$jobId'
      preLoaderRoute: typeof AuthenticatedAdminImportJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminImportJobIdRoute: typeof AuthenticatedAdminImportJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminImportJobIdRoute: AuthenticatedAdminImportJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicKultunautImportRouteChildren {
  ApiPublicKultunautImportProcessRoute: typeof ApiPublicKultunautImportProcessRoute
  ApiPublicKultunautImportStatusRoute: typeof ApiPublicKultunautImportStatusRoute
}

const ApiPublicKultunautImportRouteChildren: ApiPublicKultunautImportRouteChildren =
  {
    ApiPublicKultunautImportProcessRoute: ApiPublicKultunautImportProcessRoute,
    ApiPublicKultunautImportStatusRoute: ApiPublicKultunautImportStatusRoute,
  }

const ApiPublicKultunautImportRouteWithChildren =
  ApiPublicKultunautImportRoute._addFileChildren(
    ApiPublicKultunautImportRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BiografSlugRoute: BiografSlugRoute,
  ByCityRoute: ByCityRoute,
  FilmSlugRoute: FilmSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicKultunautImportRoute: ApiPublicKultunautImportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
