-- Anonymous, cookie-free product analytics. This table is deliberately
-- server-only: the public endpoint validates a strict event allowlist and
-- writes through the service-role client.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (
    event_type in ('page_view', 'filter_change', 'zero_results', 'ticket_click')
  ),
  path text not null check (char_length(path) between 1 and 300),
  item_type text check (item_type is null or item_type in ('movie', 'cinema')),
  item_id text check (item_id is null or char_length(item_id) <= 160),
  filter_name text check (filter_name is null or char_length(filter_name) <= 80),
  filter_value text check (filter_value is null or char_length(filter_value) <= 160),
  is_active boolean
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_type_created_at_idx
  on public.analytics_events (event_type, created_at desc);

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from public, anon, authenticated;
revoke all on sequence public.analytics_events_id_seq from public, anon, authenticated;
grant all on table public.analytics_events to service_role;
grant all on sequence public.analytics_events_id_seq to service_role;

comment on table public.analytics_events is
  'Private, anonymous product events. No visitor ID, IP address or referrer is stored.';
